import { StyleSheet, View } from 'react-native';
import { APP_CONFIG } from '@/constants/config';
import { colors, spacing } from '@/constants/theme';
import { AppText } from '@/components/ui/AppText';
import { Card } from '@/components/ui/Card';
import { InfoRow } from '@/components/ui/InfoRow';
import { LogoMark } from '@/components/ui/Logo';
import { MetaBadge } from '@/components/ui/StatusBadge';
import { formatDate, formatMoney, formatPeriod } from '@/lib/utils/format';
import { paymentMethodLabel } from '@/lib/utils/meta';
import { paymentStatusMeta } from '@/lib/utils/status';
import type { Payment } from '@/types';

interface Props { payment: Payment; tenantName: string; unitNumber: string; propertyName: string; landlordName: string }

export function ReceiptView({ payment, tenantName, unitNumber, propertyName, landlordName }: Props) {
  const balance = payment.expectedAmount - payment.amount;
  return (
    <Card>
      <View style={styles.head}>
        <LogoMark size={36} />
        <View style={{ flex: 1 }}>
          <AppText variant="heading">Rent receipt</AppText>
          <AppText variant="caption" color={colors.textMuted}>{APP_CONFIG.name}</AppText>
        </View>
      </View>
      <View style={styles.amountBox}>
        <AppText variant="caption" color={colors.textMuted}>Amount received</AppText>
        <AppText variant="display" color={colors.success}>{formatMoney(payment.amount)}</AppText>
        <MetaBadge meta={paymentStatusMeta[payment.status]} />
      </View>
      <View style={styles.rule} />
      <InfoRow label="Tenant" value={tenantName} />
      <InfoRow label="Unit" value={unitNumber} />
      <InfoRow label="Property" value={propertyName} />
      <InfoRow label="Landlord" value={landlordName} />
      <InfoRow label="Rent period" value={formatPeriod(payment.period)} />
      <InfoRow label="Payment date" value={payment.paidDate ? formatDate(payment.paidDate) : '-'} />
      <InfoRow label="Method" value={payment.method ? paymentMethodLabel[payment.method] : '-'} />
      <InfoRow label="Reference" value={payment.reference ?? 'Not applicable'} />
      {balance > 0 ? <InfoRow label="Balance remaining" value={formatMoney(balance)} /> : null}
      <View style={styles.rule} />
      <AppText variant="caption" color={colors.textMuted} align="center">Generated by {APP_CONFIG.name}. Keep this receipt for your records.</AppText>
    </Card>
  );
}

const styles = StyleSheet.create({
  head: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  amountBox: { alignItems: 'center', gap: spacing.xs, paddingVertical: spacing.xl },
  rule: { height: 1, backgroundColor: colors.border, marginVertical: spacing.md },
});
